package com.example.listadecomprasmatalv.DataStore

import com.example.listadecomprasmatalv.DataClasses.Store
import com.example.listadecomprasmatalv.DataClasses.StoreItem
import com.example.listadecomprasmatalv.R

object StoreData {
    val stores = listOf(
        Store(
            1,
            "Almacén Pedro",
            "9:00 - 15:00",
            "Almacén",
            "Avenida Vet. 123",
            R.drawable.shopicon1,
            "Almacén de proviciones básicas y esenciales.",
            "Efectivo, Debito",
            "N/A",
            "support@almacenpedro.com",
            listOf(
                StoreItem(StoreListData.baseItems[0].itemId,
                    StoreListData.baseItems[0].itemName,
                    StoreListData.baseItems[0].itemImageResourceId,
                    StoreListData.baseItems[0].itemType,
                    800,
                    "Almacén Pedro",
                    StoreListData.baseItems[0].units,
                    StoreListData.baseItems[0].measurement,
                    0.0),
                StoreItem(StoreListData.baseItems[1].itemId,
                    StoreListData.baseItems[1].itemName,
                    StoreListData.baseItems[1].itemImageResourceId,
                    StoreListData.baseItems[1].itemType,
                    700,
                    "Almacén Pedro",
                    StoreListData.baseItems[1].units,
                    StoreListData.baseItems[1].measurement,
                    0.0),
                StoreItem(StoreListData.baseItems[2].itemId,
                    StoreListData.baseItems[2].itemName,
                    StoreListData.baseItems[2].itemImageResourceId,
                    StoreListData.baseItems[2].itemType,
                    600,
                    "Almacén Pedro",
                    StoreListData.baseItems[2].units,
                    StoreListData.baseItems[2].measurement,
                    0.0),
                StoreItem(StoreListData.baseItems[3].itemId,
                    StoreListData.baseItems[3].itemName,
                    StoreListData.baseItems[3].itemImageResourceId,
                    StoreListData.baseItems[3].itemType,
                    1000,
                    "Almacén Pedro",
                    StoreListData.baseItems[3].units,
                    StoreListData.baseItems[3].measurement,
                    0.0),
                StoreItem(StoreListData.baseItems[4].itemId,
                    StoreListData.baseItems[4].itemName,
                    StoreListData.baseItems[4].itemImageResourceId,
                    StoreListData.baseItems[4].itemType,
                    1200,
                    "Almacén Pedro",
                    StoreListData.baseItems[4].units,
                    StoreListData.baseItems[4].measurement,
                    0.0),
            )
        ),
        Store(
            2,
            "Farmacia Colmada",
            "8:00 - 18:00",
            "Farmacia",
            "Avenida Norte 456",
            R.drawable.pharmacyicon1,
            "Farmacia Colmada vende varios remedios y productos cosmeticos.",
            "Efectivo, Credito",
            "https://www.farmaciacolmada.com",
            "support@farmaciacolmada.com",
            listOf(
                StoreItem(StoreListData.baseItems[5].itemId,
                    StoreListData.baseItems[5].itemName,
                    StoreListData.baseItems[5].itemImageResourceId,
                    StoreListData.baseItems[5].itemType,
                    StoreListData.baseItems[5].basePrice,
                    "Farmacia Colmada",
                    StoreListData.baseItems[5].units,
                    StoreListData.baseItems[5].measurement,
                    0.0),
                StoreItem(StoreListData.baseItems[6].itemId,
                    StoreListData.baseItems[6].itemName,
                    StoreListData.baseItems[6].itemImageResourceId,
                    StoreListData.baseItems[6].itemType,
                    StoreListData.baseItems[6].basePrice,
                    "Farmacia Colmada",
                    StoreListData.baseItems[6].units,
                    StoreListData.baseItems[6].measurement,
                    0.0),
                StoreItem(StoreListData.baseItems[7].itemId,
                    StoreListData.baseItems[7].itemName,
                    StoreListData.baseItems[7].itemImageResourceId,
                    StoreListData.baseItems[7].itemType,
                    StoreListData.baseItems[7].basePrice,
                    "Farmacia Colmada",
                    StoreListData.baseItems[7].units,
                    StoreListData.baseItems[7].measurement,
                    0.0),
            )
        ),
        Store(
            3,
            "Ultramercado",
            "9:00 - 22:00",
            "Supermercado",
            "Calle Principal 21",
            R.drawable.supermarketicon1,
            "Ultramercado posee varios recursos y productos de varias marcas.",
            "Efectivo, Credito, Debito",
            "https://www.ultramercado.cl",
            "support@ultramercado.com",
            listOf(
                StoreItem(StoreListData.baseItems[0].itemId,
                    StoreListData.baseItems[0].itemName,
                    StoreListData.baseItems[0].itemImageResourceId,
                    StoreListData.baseItems[0].itemType,
                    StoreListData.baseItems[0].basePrice,
                    "Ultramercado",
                    StoreListData.baseItems[0].units,
                    StoreListData.baseItems[0].measurement,
                    0.0),
                StoreItem(StoreListData.baseItems[1].itemId,
                    StoreListData.baseItems[1].itemName,
                    StoreListData.baseItems[1].itemImageResourceId,
                    StoreListData.baseItems[1].itemType,
                    StoreListData.baseItems[1].basePrice,
                    "Ultramercado",
                    StoreListData.baseItems[1].units,
                    StoreListData.baseItems[1].measurement,
                    0.0),
                StoreItem(StoreListData.baseItems[2].itemId,
                    StoreListData.baseItems[2].itemName,
                    StoreListData.baseItems[2].itemImageResourceId,
                    StoreListData.baseItems[2].itemType,
                    StoreListData.baseItems[2].basePrice,
                    "Ultramercado",
                    StoreListData.baseItems[2].units,
                    StoreListData.baseItems[2].measurement,
                    0.0),
                StoreItem(StoreListData.baseItems[3].itemId,
                    StoreListData.baseItems[3].itemName,
                    StoreListData.baseItems[3].itemImageResourceId,
                    StoreListData.baseItems[3].itemType,
                    StoreListData.baseItems[3].basePrice,
                    "Ultramercado",
                    StoreListData.baseItems[3].units,
                    StoreListData.baseItems[3].measurement,
                    0.0),
                StoreItem(StoreListData.baseItems[4].itemId,
                    StoreListData.baseItems[4].itemName,
                    StoreListData.baseItems[4].itemImageResourceId,
                    StoreListData.baseItems[4].itemType,
                    StoreListData.baseItems[4].basePrice,
                    "Ultramercado",
                    StoreListData.baseItems[4].units,
                    StoreListData.baseItems[4].measurement,
                    0.0),
                StoreItem(StoreListData.baseItems[5].itemId,
                    StoreListData.baseItems[5].itemName,
                    StoreListData.baseItems[5].itemImageResourceId,
                    StoreListData.baseItems[5].itemType,
                    4000,
                    "Ultramercado",
                    StoreListData.baseItems[5].units,
                    StoreListData.baseItems[5].measurement,
                    0.0),
                StoreItem(StoreListData.baseItems[6].itemId,
                    StoreListData.baseItems[6].itemName,
                    StoreListData.baseItems[6].itemImageResourceId,
                    StoreListData.baseItems[6].itemType,
                    3500,
                    "Ultramercado",
                    StoreListData.baseItems[6].units,
                    StoreListData.baseItems[6].measurement,
                    0.0),
                StoreItem(StoreListData.baseItems[7].itemId,
                    StoreListData.baseItems[7].itemName,
                    StoreListData.baseItems[7].itemImageResourceId,
                    StoreListData.baseItems[7].itemType,
                    3000,
                    "Ultramercado",
                    StoreListData.baseItems[7].units,
                    StoreListData.baseItems[7].measurement,
                    0.0),
            )
        )
    )
}
